# Generated by Django 3.1.7 on 2021-05-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210516_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('s', 'shirt'), ('sw', 'sportWear'), ('ow', 'outWear')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='describtion',
            field=models.TextField(default='test Describtion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('s', 'secondary'), ('p', 'primary'), ('d', 'danger')], default='p', max_length=2),
            preserve_default=False,
        ),
    ]
