# Generated by Django 3.1.7 on 2021-05-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210516_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='New', max_length=200),
            preserve_default=False,
        ),
    ]
