# Generated by Django 3.1.7 on 2021-05-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='defaulte.jpg', upload_to='static/img'),
        ),
    ]
