# Generated by Django 3.2.5 on 2021-07-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_itemvariation_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_variation',
            field=models.ManyToManyField(to='catalog.ItemVariation'),
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
